# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
import starlette
from fastapi import params

from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args


class AbstractMovieService(AbstractFernService):
    """
    AbstractMovieService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def upload_movie(self, *, name: fastapi.Form, contents: typing.Sequence[params.UploadFile], movie_id: str) -> None:
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_upload_movie(router=router)

    @classmethod
    def __init_upload_movie(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.upload_movie)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "name":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "contents":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "movie_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.upload_movie, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.upload_movie)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.upload_movie(*args, **kwargs)
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'upload_movie' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.upload_movie.__globals__)

        router.post(
            path="/movie/movie/{movie_id}",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractMovieService.upload_movie.__doc__,
            **get_route_args(cls.upload_movie, default_tag="movie"),
        )(wrapper)
