# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from .actress import Actress


class Person_Actor(pydantic.BaseModel):
    type: typing_extensions.Literal["actor"]
    value: str

    class Config:
        frozen = True


class Person_Actress(Actress):
    type: typing_extensions.Literal["actress"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class Person_Director(pydantic.BaseModel):
    type: typing_extensions.Literal["director"]

    class Config:
        frozen = True


Person = typing.Union[Person_Actor, Person_Actress, Person_Director]
