# This file was auto-generated by Fern from our API Definition.

import typing

from .commons.metadata.metadata import Metadata

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class Node(pydantic.BaseModel):
    """
    from seed import Node
    from seed.commons import Metadata

    Node(
        id="node-8dvgfja2",
        label="left",
        metadata=Metadata(
            id="metadata-kjasf923",
            data={"foo": "bar", "baz": "qux"},
        ),
    )
    """

    id: str
    label: typing.Optional[str]
    metadata: typing.Optional[Metadata]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)
