# This file was auto-generated by Fern from our API Definition.

import typing

from ...with_metadata import WithMetadata
from .movie import Movie
from .with_docs import WithDocs


class Response(WithMetadata, WithDocs):
    data: Movie

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)
