# This file was auto-generated by Fern from our API Definition.

import typing

from .docs import Docs


class Json(Docs):
    """
    from seed import Json

    Json(
        docs="Types extend this type to include a docs and json property.",
        raw='{"docs": true, "json": true}',
    )
    """

    raw: str

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)
