name: Build seed container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fernapi/python-seed
          tags: |
            type=sha
            latest

        # TODO: Only publish one base image for Seed if this becomes a monorepo
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/seed/Dockerfile
          platforms: linux/amd64,linux/arm64
          # use short SHA if modded, or just use latest if nothing changed
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
